### ISSUE TITLE
No description how to restore missed original data after decoding

### ISSUE THREAD

**Issue by awson** [catid/leopard#13]
I've looked into `benchmark.cpp` and the only place `decode_work_data` is used is at https://github.com/catid/leopard/blob/b58d1eaf59e263d25e473a3460437e19386956eb/tests/benchmark.cpp#L493.

Thus i conjecture `decode_work_data[i]` has CRC32 in first 4 bytes, then the length of data in next 4 bytes, and then the data (which correspond to missed `original_data[i]`) itself in remaining (length) data(?).

But if this hypothesis is correct then we should have extra 8 bytes room in each `decode_work_data[i]`, but the code uses `buffer_bytes` only (exactly as for any other buffer).

If the hypothesis is wrong then where should we extract missed `original_data[i]` from?

**Comment by catid** [comment]
I think you're right.  Usually there is some way in an app to check the validity of the data.

One way to do it would be to set `app_data_bytes = buffer_bytes - 8`, and then `original_data` would contain `[CRC] [LEN] [APP DATA]` and the `decode_work_data` can be checked for validity as you suggested

**Comment by cjh680** [comment]
> I've looked into `benchmark.cpp` and the only place `decode_work_data` is used is at
> 
> https://github.com/catid/leopard/blob/b58d1eaf59e263d25e473a3460437e19386956eb/tests/benchmark.cpp#L493
> 
> .
> Thus i conjecture `decode_work_data[i]` has CRC32 in first 4 bytes, then the length of data in next 4 bytes, and then the data (which correspond to missed `original_data[i]`) itself in remaining (length) data(?).
> 
> But if this hypothesis is correct then we should have extra 8 bytes room in each `decode_work_data[i]`, but the code uses `buffer_bytes` only (exactly as for any other buffer).
> 
> If the hypothesis is wrong then where should we extract missed `original_data[i]` from?

Hello, did you find the solution? I have a question about "how to recover the missed original data after decoding". I found that I can't recover the missed original data after decoding.
