### ISSUE TITLE
 recovery_count > original_count

### ISSUE THREAD

**Issue by foobar2019** [catid/leopard#14]
As the title says, I have small original count, large recovery and need to pad up to 32k/32k. The complexity is not pretty (though still best one can get for a MDS). 
Would it be possible to arrange the field so as to avoid the overhead?

I can see some attempts in encodeL(), but indeed as the prototype code says, it doesn't seem to work, or would need specialized decoder. Is this inherent limitation of the algorithm, or just not implemented?

**Comment by catid** [comment]
It's just not implemented.  I probably have a bug in that code preventing
it from working.  Currently not planning on improving this codebase

**Comment by foobar2019** [comment]
Thanks for clarification. I'll try to fiddle with it some more then if it can be made sparse.

**Comment by AndersTrier** [comment]
For anyone hitting this issue:
Markus Laire implementation of the same algorithm allows "Any combination of 1 - 32768 original shards with 1 - 32768 recovery shards.": https://github.com/malaire/reed-solomon-16
I added some SIMD code to make it about 10x faster: https://crates.io/crates/reed-solomon-simd

**Comment by catid** [comment]
> For anyone hitting this issue: Markus Laire implementation of the same algorithm allows "Any combination of 1 - 32768 original shards with 1 - 32768 recovery shards.": https://github.com/malaire/reed-solomon-16 I added some SIMD code to make it about 10x faster: https://crates.io/crates/reed-solomon-simd

Awesome work!

**Comment by AndersTrier** [comment]
> > For anyone hitting this issue: Markus Laire implementation of the same algorithm allows "Any combination of 1 - 32768 original shards with 1 - 32768 recovery shards.": https://github.com/malaire/reed-solomon-16 I added some SIMD code to make it about 10x faster: https://crates.io/crates/reed-solomon-simd
> 
> Awesome work!

Well, thanks! And likewise!

How about linking (from the Readme) to the libraries in different languages that's based on your implementation? I could make a PR doing that. I know of the following:

Go:
https://github.com/klauspost/reedsolomon

Rust:
https://github.com/AndersTrier/reed-solomon-simd
https://github.com/malaire/reed-solomon-16
https://github.com/paritytech/reed-solomon-novelpoly

I'm working on some python bindings for reed-solomon-simd as well.
